"""now cannot delete product if it in orders

Revision ID: cd6634fb85be
Revises: da851e94aabc
Create Date: 2026-06-16 19:28:25.304242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6634fb85be'
down_revision: Union[str, Sequence[str], None] = 'da851e94aabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_products_product_id_fkey'), 'orders_products', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.create_foreign_key(op.f('orders_products_product_id_fkey'), 'orders_products', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
